on:
  push:
  pull_request_target:
    branches: [master]
name: Tests / test-user-mirror
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v1
    - name: Mirror Github to Gitee with white list
      uses: ./.
      with:
        src: github/yeluo2022
        dst: gitee/hyh1219790234
        dst_key: ${{ secrets.ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC6RdGECOEbcV1sKRa00p8qWClVfJOaa5F0CC0T1/Xb7 Gitee SSH Key }}
        dst_token:  ${{ secrets.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 }}
        static_list: 'hub-mirror-action,hashes, simple-spring'
        force_update: true
        debug: true
        mappings: 'hashes=>hashes_gitee'
